language: node_js
node_js:
  - "11.10.1"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
before_install:
  - export TZ=Europe/Amsterdam
deploy:
  provider: surge
  skip_cleanup: true
  domain: messages-yvln.surge.sh
  project: ./build/
on:
branch: master